twolook_oll_algorithms = {
    "line": "F R U R' U' F'",
    "angle": "F U R U' R' F'",
    "dot": "F R U R' U' F' U2 F U R U' R' F'",
    "sune": "R U R' U R U2 R'",
    "anti-sune": "R U2 R' U' R U' R'",
    "h": "F R U R' U' R U R' U' R U R' U' F'",
    "pi": "R U2 R2 U' R2 U' R2 U2 R",
    "t": "R M' U R' U' R' M F R F'",
    "l": "F' R M' U R' U' R' M F R",
    "u": "R2 D R' U2 R D' R' U2 R'",
}

oll_algorithms = {
  "1": "R U2 R2 F R F' U2 R' F R F'",
  "2": "F R U R' U' F' R M U R' U' M'",
  "3": "R M U R' U' M' U' F R U R' U' F'",
  "4": "R M U R' U' M' U F R U R' U' F'",
  "5": "R' M U2 R U R' U R M",
  "6": "R M' U2 R' U' R U' R' M",
  "7": "R M' U R' U R U2 R' M",
  "8": "L M U' L U' L' U2 L M'",
  "9": "R U R' U' R' F R2 U R' U' F'",
  "10": "R U R' U R' F R F' R U2 R'",
  "11": "R M' U R' U R U' R' U' R' M R U R U' R'",
  "12": "M' R' U' R U' R' U2 R U' M",
  "13": "R M' U' R' M U' R M' U R' M F' U F",
  "14": "R' F R U R' F' R B U' B'",
  "15": "R' M U' R M' R' U' R U R' M U R M'",
  "16": "R M' U R' M R U R' U' R M' U' R' M",
  "17": "F R U R' U' F' R M' U R U' R' M",
  "18": "F R U R' U' R M U R' U' M' U' F'",
  "19": "M U R U R' U' M' R' F R F'",
  "20": "R M' U R' U' M2 U R U' R' U' M'",
  "21": "R U2 R' U' R U R' U' R U' R'",
  "22": "R U2 R2 U' R2 U' R2 U2 R",
  "23": "R2 D R' U2 R D' R' U2 R'",
  "24": "R M' U R' U' R' M F R F'",
  "25": "F' R M' U R' U' R' M F R",
  "26": "R U2 R' U' R U' R'",
  "27": "R U R' U R U2 R'",
  "28": "R M' U R' U' M U R U' R'",
  "29": "R2 U' R' U' R U R U R U' R",
  "30": "R2 U R' U R U' R' U' R' U R'",
  "31": "R' U' F U R U' R' F' R",
  "32": "R U B' U' R' U R B R'",
  "33": "R U R' U' R' F R F'",
  "34": "R U R' U' B' R' F R F' B",
  "35": "R U2 R2' F R F' R U2 R'",
  "36": "L' U' L U' L' U L U L F' L' F",
  "37": "F R' F' R U R U' R'",
  "38": "R U R' U R U' R' U' R' F R F'",
  "39": "L F' L' U' L U F U' L'",
  "40": "R' F R U R' U' F' U R",
  "41": "R U R' U R U2 R' F R U R' U' F'",
  "42": "R' U' R U' R' U2 R F R U R' U' F'",
  "43": "R M U R' U' M'",
  "44": "F U R U' R' F'",
  "45": "F R U R' U' F'",
  "46": "R' U' R' F R F' U R",
  "47": "F' L' U' L U L' U' L U F",
  "48": "F R U R' U' R U R' U' F'",
  "49": "R M' U' R2 M2 U R2 M2 U R2 M2 U' R M'",
  "51": "R M U R' U' M' U F R U R' U' F'",
  "52": "R U R' U R U' B U' B' R'",
  "53": "R' M U' R U' R' U R U' R' U2 R M'",
  "54": "R M' U R' U R U' R' U R U2 R' M",
  "55": "R' F R U R' U' F' U R",
  "56": "R M' U R' M U R U' R' U R U' R' R M' U' R' M",
  "57": "R U R' U' M' U R U' R' M"
}

speedcubedb_oll_algorithms = [
  {
    "case": "OLL 1",
    "algorithms": [
      "R U2 R2 F R F' U2 R' F R F'",
      "y R U' R2 D' r U' r' D R2 U R'",
      "f R U R' U' R f' U' r' U' R U M'",
      "L' U2 L2 F' L' F U2 L F' L' F",
      "R' U' F R' F' R2 U R f' U' f",
      "r' U' R U' R' U2 r U r U2 R' U' R U' r'",
      "R U B' R B R2 U' R' F R F'",
      "F R U R' U' F' S R U R' U' R' F R f'",
      "y R' U R2 D r' U r D' R2 U' R",
      "F R U R' U' S F' R U R' U' R' F R f'",
      "M R U R' U R U' R' U r U2 r' U' M'",
      "r U R' U R' r2 U' R' U R' r2 U2 r'",
      "R U f' U f R2 U' R' F R F'",
      "U' R U' R2 D' r U' r' D R2 U R'",
      "R U R' S R' U' R U R S' U F R' F' R",
      "F R U R' U' F' U2 F U R U' R' F' r U R' U' r' F R F'",
      "y R U R' U' R' F R F' U2 R U R' U R U' R' U' R' F R F'",
      "r f R' U l F2 U' F' r U r'",
      "r f R' d f R2 d' F' r U r'",
      "r U2 R2 U' R U' r' U2 F R F'",
      "R U R' U R U' R' U R U2 R' S R' U' R U R U R U' R' S'",
      "R U R' d' R' F' R U2 M' U' M F R' F' r U R U' r'",
      "y F U R U' R' F' R U R' U R U' y R U' R' F'",
      "y S U F R2 U' R2 U' R2 U R2 f'",
      "r U R' U R' r2 U' R' U R' r2 U2 r' U'",
      "y' R U' R2 D' r U' r' D R2 U R'",
      "R U2 R' l' U l F' U2 R' F R F'",
      "y L' U L2 D l' U l D' L2 U' L",
      "U F R' F' R U S' R U' R' y' r U' r' F R' F' r",
      "U R U R' U R' F R F' U2 y' r' U' R U M'",
      "F R' F' R U2 R U' R' y' r' U r U' r' U' r",
      "y F U R' F R F2 U' y' R' F R F'",
      "y F U R' F R F2 U' F' L F L'",
      "R U B' l U l2 x' U' R' F R F'",
      "y F R U R' U' F' r' U r2 U' r2 U' r2 U r'"
    ]
  },
  {
    "case": "OLL 2",
    "algorithms": [
      "y' R U' R2 D' r U r' D R2 U R'",
      "F R U R' U' S R U R' U' f'",
      "F R U R' U' F' f R U R' U' f'",
      "y r U r' U2 R U2 R' U2 r U' r'",
      "y2 f U R U' R' S' U R U' R' F'",
      "R' U2 r U' r' U2 r U r' U2 R",
      "y r U r' U2 r U2 R' U2 R U' r'",
      "y L F L' U2 R U2 R' U2 L F' L'",
      "y2 F R' F' R U2 F R' F' R2 U2 R'",
      "y R' F' r U2 r' F2 R U2 R' F R",
      "r' D R2 U R' U2 R U' R2 D' r",
      "F R' F' U2 r U R' U R2 U2 r'",
      "F R U r' U' R U R' M' U' F'",
      "y' r' U' R U2 R' U2 r U2 r' U r",
      "y R' F' r U2 L' U2 l U2 R' F R",
      "R' F' U' f U' R U R' S' U R",
      "y r U R' U2 R U2 r' U2 r U' r'",
      "U r U r' U2 r U2 R' U2 R U' r'",
      "y' L' U R L U2 R' U L F' L' F U R' F R F'",
      "y l' U' l U2 L' U2 L U2 R' F R",
      "y R' U R2 D r' U' r D' R2 U' R",
      "y R' F' R U2 r' F2 r U2 R' F R",
      "y2 F R' F' R2 U R' F' U2 F U' R U' R'",
      "y2 R U R' U F' U2 F R U' R2 F R F'",
      "M' U' r' F R U F U' R U R' U' F'",
      "y l' U' l U2 L' U2 L U2 l' U l",
      "y R' F' R U2 L' U2 L U2 R' F R",
      "y2 F' L' U' L U S' L' U' L U f",
      "F R U R' U' F' U2 F U R U' R' F'",
      "y L F U F' U' E d E' U' S l x U R' U' f'",
      "y L F U F' U' E d E' U' S R U R' U' f'",
      "F R F' U2 F R2 f' U2 f R' F'",
      "y' F R' F' R U2 F R' F' R U2 R' F R U R U' R' F'",
      "y l' U' l U2 l' U2 L U2 L' U l",
      "y' l U L' U2 L U2 l' U2 l U' l'",
      "y2 F U R U' R' F' R' U' R' F R F' U R",
      "y2 f U R U' R' f' F U R U' R' F'",
      "U L F L' U2 R U2 R' U2 r U' r'",
      "R U2 R2 F R F' U2 R' F R F' U2 F R' F' r U R U' r'",
      "y' F R U' R' F R U' R' F' L' U L F' L' U L",
      "y' L' U L2 D l' U' l D' L2 U' L",
      "U' R U' R2 D' r U r' D R2 U R'",
      "r' U' r R' U' R U' R' U R U2 r' U r",
      "U' R2 F R F' U' R U' R2 F R F' U R",
      "U' F R' F' R U' F' U' r U2 R' U r' F2 R",
      "U' R U R' S U' R' U S' U R' U F' U F R",
      "U2 F R' F' R U2 F R' F' R2 U2 R'",
      "U F R' F' R U2 R U' R' F' r' F2 r U F",
      "U R U R' U' R f R f' U R' F' U' r U' r' F2",
      "F R' F' R U R U' f R f' U R' U' R U' R'",
      "R U R' U2 F' U' L' U L U F U' R U2 R'",
      "y' r' U' r U2 R' U2 R U2 r' U r",
      "y' R' F R F' U2 R' F R F2 U2 F",
      "y' R' F R F' U2 R' F R y' R2 U2 R",
      "U2 R U S R' U R U' F R' f' R'",
      "U' F' L' U L F' L' U L F U' R' F R2 U' R'"
    ]
  },
  {
    "case": "OLL 3",
    "algorithms": [
      "y' f R U R' U' f' U' F R U R' U' F'",
      "y R' F2 R2 U2 R' F R U2 R2 F2 R",
      "r' R2 U R' U r U2 r' U M'",
      "M R U R' U r U2 r' U M'",
      "f U R U' R' S' R' F' R U R U' R'",
      "y F U R U' R' F' U F R U R' U' F'",
      "F U2 F R' F' R U R U R' U F'",
      "y2 M' U r' U2 r U R' U R2 r'",
      "M U l' U2 l U L' U L M'",
      "y' f R U R' U' f' U f U R U' R' f'",
      "y' x' R U2 R2 F2 R U R' F2 R2 U2 R' x",
      "y2 R' U F' U F U F R' F' R U2 R",
      "f U R U' R' S' R U' R' U' R U R' F'",
      "y F R U R' U' R U R' U' F' U' F R U R' U' F'",
      "L' l U l' U2 l U L' U L M'",
      "y f' L' U' L U f U F R U R' U' F'",
      "R r' U R' F2 R U r' F r2 R'",
      "R f' U' f U R D r' U' r D' R'",
      "y' F R U R' U' F' U f' L' U' L U f",
      "y' F R U R' U' F' U2 R' U' F' U F R",
      "r' R U R' F2 R U L' U L M'",
      "L F' L' F U S' L U L' U' L' S",
      "y' R U R' U' R' F R F' U f' L' U' L U f",
      "y2 M' L U L' U l U2 l' U M",
      "S R U R' U' f' U' F R U R' U' B' R' F R S z'",
      "R U R' S U R U' R' S2 R U' R' S",
      "y F R U' R' U' R U R' U' R' F R F' R U R' F'",
      "U F R U' R' U' R U R' U' R' F R F' R U R' F'",
      "y' F R U R' U' F' R U R' F' U2 F R U' R'",
      "U' F R U R' U' F' R U R' F' U2 F R U' R'",
      "y R' D' r U' r' D R U F R' F' R",
      "y' F' U' L' U L F U' F R U R' U' F'",
      "y2 l' L2 U L' U l U2 l' U M",
      "L' U' L U L F' L' S' L' U' L U f",
      "F R' F' R U' S U' R U R' S' R U R'",
      "y' f R U R' U' f' R' F' U' F U R",
      "y2 L F U F' U' F U F' U' L' y' L F U F' U' L'",
      "y' F' U' L' U L F L F U F' U' L'",
      "U' f R U R' U' f' U' F R U R' U' F'",
      "r' R2 U R' U r U2 r' U r R'",
      "L' l U R' F2 R U L' U L r R'",
      "L' R2 B R' B L U2 L' B M' x'",
      "y' F R' F' R U R U' R' U' R U R' U' R' F R F'",
      "r' R2 U R' U r U2 r' U R' r",
      "y2 R' U' F' U F R F R U R' U' F'",
      "r U R' U R U2 r' U r U R' U' r' R U R U' R'",
      "y L U2 L F' L' F U F U F' U L'",
      "y' S U R U R2 U' R2 U R U S'",
      "y L F2 L2 U2 L F L' U2 L2 F2 L'",
      "y f' L' U' L U f U' F' L' U' L U F"
    ]
  },
  {
    "case": "OLL 4",
    "algorithms": [
      "y' R' F2 R2 U2 R' F' R U2 R2 F2 R",
      "y' f R U R' U' f' U F R U R' U' F'",
      "R' F R F' U' S R' U' R U R S'",
      "y F U R U' R' F' U' F R U R' U' F'",
      "l L2 U' L U' l' U2 l U' M'",
      "y2 M' R' U' R U' r' U2 r U' M",
      "R U R' U' R' F R S R U R' U' f'",
      "y x' R U2 R2 F2 R U' R' F2 R2 U2 R' x",
      "R r2 F' r U' R' F2 R U' M'",
      "R' F' U' F U R f R U R' U' f'",
      "M U' r U2 r' U' R U' R2 r",
      "y' f R U R' U' f' U' f U R U' R' f'",
      "y F U' R U' R' U' R' F R F' U2 F'",
      "y' F R U' R' U R U R' F' f R U R' U' f'",
      "U' f R U R' U' f' U F R U R' U' F'",
      "R r' U' r U2 r' U' M' r' R2 U' R' M'",
      "y F U R U' R' F' U F' L' U' L U F",
      "r' R U' r U2 r' U' R U' R' M'",
      "r' R U' r U2 r' U' R U' R2 r",
      "M r' F' r U' R' F2 R U' M'",
      "y' f R U R' d' l' F R U R' U' F'",
      "F' U2 F' L F L' U' L' U' L U' F",
      "y' R' U2 R' F R F' U' F' U' F U' R",
      "l L' U' L F2 L' U' R U' R' M'",
      "y' S U' R' U' R2 U R2 U' R' U' S'",
      "y' F' U' L' U L F U F R U R' U' F'",
      "y2 R' M' U' R U' r' U2 r U' M",
      "y2 F' L' U' L U F U F R U' R' U' R U R' F'",
      "l' U' L U' L' U2 l U r' U' R U R' r U' R' U R",
      "y F' L F L' U' L' U L U L' U' L U L F' L' F",
      "M U' r U2 r' U' R U' M' R'",
      "f' U' r' F r S r U r' U' r' F r",
      "U' R' F2 R2 U2 R' F' R U2 R2 F2 R",
      "y' F' L' U L U L' U' L U L F' L' F L' U' L F",
      "y2 R' F R F' U' R' D' r U r' D R",
      "y2 F R' F' R U R U' R' U R U R' U' R' F R F'",
      "f R U R' U' f' y R' F R U R' U' F' U R",
      "L' U' L U' L' U2 L S' R U R' S U' M' U R U' r'",
      "y2 L F U F' U' F U F' U' L' F R U R' U' F'",
      "y F' L' U' L U F U' f R U R' U' f'",
      "L' U' L U' L' U2 L R U R' U' M' U R U' r' U2 r U R' U' M U R U' R'",
      "y f' L' U' L U f U F' L' U' L U F",
      "y f' L' U' L U f U' F R U R' U' F'",
      "R' F' R U' S r' F M' F R S'",
      "M L' U' L U' l' U2 l U' M'",
      "y2 r R2 U' R U' r' U2 r U' M",
      "y F U R U' R' F' R' F' U' F U R",
      "l' U' L U' L' U2 l2 U L' U' M' U L U' L'",
      "y2 M' R' U' R U' r' U2 r U' r' R",
      "U' R' U' F' U' F R U' R' F' U' F U' R",
      "y2 r' U' R U' R' U2 r2 U R' U' M U R U' R'",
      "y' f' U' L' U L f L U F U' F' L'",
      "y' L F2 L2 U2 L F' L' U2 L2 F2 L'"
    ]
  },
  {
    "case": "OLL 5",
    "algorithms": [
      "r' U2 R U R' U r",
      "y2 l' U2 L U L' U l",
      "y2 R' F2 r U r' F R",
      "y2 R' F2 L F L' F R",
      "y B' R2 F R F' R B",
      "F R U R' U' F' U' F R U R' U' F'",
      "y2 l' U2 L U r' F R",
      "U2 l' U2 L U L' U l",
      "y2 F U' R2 D R' U R D' R2 U F'",
      "y' F U R U2 R' U' R U R' U R U' R' F'",
      "y R U R2 F R F' U' F' U2 F",
      "y2 R' U' R d' R2 B' R' B R'",
      "y2 R U' R2 U' R U R' U' R' U R2 U' R2 U' R U' R' U' B U B' U2 R' U R",
      "y2 F R' F R F2 r' F2 r",
      "y2 R' F R' F' R2 y U' R U' R'",
      "y' F' r2 F r U' r F"
    ]
  },
  {
    "case": "OLL 6",
    "algorithms": [
      "r U2 R' U' R U' r'",
      "F U' R2 D R' U' R D' R2 U F'",
      "y2 l U2 L' U' L U' l'",
      "L F2 l' U' l F' L'",
      "y' F R2 B' R' B R' F'",
      "y2 R U R2 F R F2 U F",
      "R U' R' U2 r U' r' U' r U r'",
      "L F2 R' F' R F' L'",
      "y2 R B2 r' U' r B' R'",
      "y' x' D R2 U' R' U R' D' x",
      "F R U R' U' F' U' F U R U' R' F'",
      "F R U R' U' F' U f R U R' U' f'",
      "y2 F' L' U' L U F U F' L' U' L U F",
      "F' U' F2 R' F' R U R U2 R'",
      "R U R' U' R' F R F' y S R U R' U' R' F R f'",
      "y' R' F R' F' R2 B U2 B'",
      "y2 R U R' U y' R2 F R F' R",
      "y B r2 B' r' U r' B'",
      "U2 l U2 L' U' L U' l'"
    ]
  },
  {
    "case": "OLL 7",
    "algorithms": [
      "r U R' U R U2 r'",
      "S' R U R' U R U2 R' U S",
      "L' U2 L U2 L F' L' F",
      "y2 f R U R' U' f' y2 F R' F' r U R U' r'",
      "y2 l U L' U L U2 l'",
      "F R' F' R U2 R U2 R'",
      "r U r' U R U' R' r U' r'",
      "y2 R' U2 R U2 R f' U' f",
      "L F R' F R F2 L'",
      "y F U R U' R' U R U' R' F' r U2 R' U' R U' r'",
      "R U R' U R U3 R' U' M' U R U' r'",
      "r U R' U' M U2 R U2 R'",
      "y x2 F r D' r F r2 F' x2",
      "r' F2 r U2 L F' L' F",
      "R U R' U R U' R' U' M' U R U' r'",
      "y' F R B' R B R2 F'"
    ]
  },
  {
    "case": "OLL 8",
    "algorithms": [
      "y2 r' U' R U' R' U2 r",
      "l' U' L U' L' U2 l",
      "R U2 R' U2 R' F R F'",
      "R' F' r U' r' F2 R",
      "S L' U' L U' L' U2 L U' S'",
      "y2 r' U' r U' R' U R r' U r",
      "R' F' r U' L' U2 l",
      "U R U2 R2 F R F' U' R U R' U' R U' R'",
      "y2 R U' R' L' U2 L R U' R' F2 R' F' R F'",
      "l' U' l U' L' U L l' U l",
      "R' F R U' R' F' R U2 L' U' L",
      "y' R' F R F' U2 F' U2 F",
      "U2 L' B' R B' R' B2 L",
      "y x2 B' r' D r' B' r2 B x2",
      "R' F' R U' L' U L R' F R",
      "U2 r' U' R U' R' U2 r",
      "y' B' R' F R' F' R2 B",
      "R' F' L F' L' F2 R",
      "y2 L' B' L U' R' U R L' B L",
      "F' L F L' U2 L' U2 L"
    ]
  },
  {
    "case": "OLL 9",
    "algorithms": [
      "y R U R' U' R' F R2 U R' U' F'",
      "R U2 R' U' S' R U' R' S",
      "y2 F' U' F r U' r' U r U r'",
      "y' L' U' L U' L F' L' F L' U2 L",
      "y2 R' U' R U' R' U R' F R F' U R",
      "y R' U' R y r U' r' U r U r'",
      "y R' U' R y' x' R U' R' F R U R' x",
      "y' r' F' r U' r U' r' F r' F2 r",
      "r' R2 U2 R' U' R U' R' U' M'",
      "S' R U2 R' U' R U' R' U2 S",
      "U R' U' R U' l U' R' U x R' U2 R",
      "y R U R' U R U2 R' f R U R' U' R U R' U' f'",
      "y R' U' R y' l U' l' U R B R'",
      "y2 S U2 R U2 R' U' R U' R' S'",
      "y l' U' l U l F' l' F R' F R F' R U R'",
      "y' L' U' L y' L F' L' U r U r'",
      "y R' F R' F' R U R U' R2 F R F' R",
      "y2 L' U' L U' L F' L' F L' U L U L F' L' F",
      "U R' U' R F R' F' U F R F'",
      "y' L' U' L y l U' l' U l U l'",
      "y R U R' F' R U2 R' U2 R' F R U' R' F R F'",
      "y' L' U' L y' L F' L' U L F L'",
      "r' R2 U2 R' U' R U' R' U' R' r",
      "y2 F' U' L' U L y' U' R U' R' U2 R",
      "U R U R' U' R' F R2 U R' U' F'",
      "y R' U' R F R' F' U F R F'",
      "y R' U' R y' R B' R' U R B R'"
    ]
  },
  {
    "case": "OLL 10",
    "algorithms": [
      "R U R' U R' F R F' R U2 R'",
      "y F U F' R' F R U' R' F' R",
      "y M' R' U2 R U R' U R U M",
      "y2 L' U' L U L F' L2 U' L U F",
      "y R' U2 R U S' R' U R S",
      "y r R2 U2 R U R' U R U R r'",
      "R U R' y R' F R U' R' F' R",
      "R U R' U l' U R U' l U2 R'",
      "y S' R' U2 R U R' U R U2 S",
      "y' r' F2 r U S r' F r S'",
      "U R U R2 F' U' F R2 U' R2 U2 R",
      "y2 L U L' y' l' U l U' l' U' l",
      "y F U R U' R' F' U' R U R' U R U2 R'",
      "y2 r' F' r U r U' r2 F' r U F",
      "R' U' R2 f R f' U' R' U R' U R",
      "R' U' R2 f l U' R' B' l U' R U z'",
      "y M' R' U2 R U R' U R U r' R",
      "y R' U2 r' R2 U R' U R U' M'",
      "R U R' y' r' U r U' r' U' r",
      "U R U R' U R' F R F' R U' R' U' R' F R F'",
      "y R U R' U R U' R' U' B' R' F R F' B",
      "y S' U2 L' U2 L U L' U L S",
      "y R U R2 F' U' F R2 U' R2 U2 R",
      "y F R U R' U' F' U R' U' R' F R F' U R",
      "y2 r U r' U' r' F r F' L F' L' F L' U' L",
      "R U R' y R' F R U' l' U' l",
      "y U' R U R' U R' F R F' R U2 R'",
      "y' M L' U2 L U L' U L U M'",
      "U r R2 U2 R U R' U R U R r'",
      "U r R2 U2 R U R' U R U M",
      "y' S r' F2 r U r' F r U2 S'",
      "y F U F' l' U l U' l' U' l",
      "U2 L U L' F' L F U' F' L' F",
      "y' L' U2 L U S L' U L S'",
      "y' l L2 U2 L U L' U L U M'",
      "y' R r' L' U2 L U L' U L U M'",
      "y2 L' U' L F L' U2 L U2 L F' L' U L F' L' F",
      "y' f R U R' U' f' U R U R' U R U2 R'",
      "y' R U R' U F' U F U' R U2 R'",
      "y F U R U' R' y U L' U L U2 L'",
      "R U R' U x R' U R U' R x' U2 R'",
      "y2 r U R' U R U' R' U' M U R U' R'",
      "y' f R f' r' U r U' r' U' r",
      "y r R2 U2 R U R' U R U M",
      "y R U R' U R' F R F' R U' R' U' R' F R F'",
      "y2 L U L' F' L F U' F' L' F"
    ]
  },
  {
    "case": "OLL 11",
    "algorithms": [
      "r' R2 U R' U R U2 R' U M'",
      "y2 r U R' U R' F R F' R U2 r'",
      "S R U R' U R U2 R' U2 S'",
      "M R U R' U R U2 R' U M'",
      "y2 S' U2 R U R' U R U2 R' S",
      "y F' L' U' L U F U F R U R' U' F'",
      "y S' U L U L' U L U2 L' S",
      "f U R U' R2 F' R U R U' R' S'",
      "y' S U R U R' U R U2 R' S'",
      "y2 M' L U L' U L U2 L' U M",
      "r' R2 U R' U R U2 R' U R' r",
      "y' R' F' U' F2 R' F' R2 U' R' U2 R",
      "y' U' r U R' U R' F R F' R U2 r'",
      "R2 r' U R' U R U2 R' U M'",
      "U2 R U R' U' R' F R F' L' U' L U L F' L' F",
      "R U R' U R U' R' S' R U' R' S",
      "R U R' U R U R' S' R U R' S",
      "U2 l' L2 U L' U L U2 L' U M",
      "y2 R U R' U' R' F R F' U2 R U R' U' R' F R F'",
      "y2 f R U R' U' R U R' U' f' U' R U R' U' R' F R F'",
      "y2 R' u' R U' R U R' u R U' R U' R'",
      "M2 r U R' U R U2 R' U M'",
      "y F' L' U' L U F U' F' L' U' L U F",
      "U2 r U R' U R' F R F' R U2 r'",
      "L' l R U R' U R U2 R' U M'",
      "y2 L F R' F R' D R D' R F2 L'",
      "y' l' U' L U' L' U2 B' l U' R' U2 R",
      "y' F' U' L' U2 L U' L' U' L U' L' U L F",
      "y' l' U' L U' L' U2 l U2 L' U' L U' L' U2 L",
      "y2 R' L2 F L' F L F2 L' F L' R",
      "y F R U R' U' F' U r U R' U R U2 r'",
      "y' l' U' L U' L' U2 x' U' R U' R' U2 R"
    ]
  },
  {
    "case": "OLL 12",
    "algorithms": [
      "y' M' R' U' R U' R' U2 R U' M",
      "F R U R' U' F' U F R U R' U' F'",
      "y' S R' U' R U' R' U2 R U2 S'",
      "y M L' U' L U' L' U2 L U' M'",
      "y' r R2 U' R U' R' U2 R U' R r'",
      "y l L2 U' L U' L' U2 L U' M'",
      "y' l' U' L U' L F' L' F L' U2 l",
      "y' r R2 U' R U' R' U2 R U' r' R",
      "S U' R' U' R U' R' U2 R S'",
      "y S' L' U' L U' L' U2 L U2 S",
      "y' M' R' U' R U' R' U2 R U' R r'",
      "y2 F U R U2 R' U R U R' U R U' R' F'",
      "y' S U2 L' U' L U' L' U2 L S'",
      "y S' r' F' r U' r' F2 r U2 S",
      "y S' U2 R' U' R U' R' U2 R S",
      "y R u R' U R' U' R u' R' U R' U R",
      "y2 r U R' U R U2 r' U2 R U R' U R U2 R'",
      "y2 S' U' L' U' L U' L' U2 L S",
      "y r' R U2 R' U' R U' R' U2 R U M'",
      "y R r2 F' r U' r' F2 r U' M'",
      "y' M' R' U' R U' R' U2 R U' r' R",
      "y' S U2 r' F' r U' r' F2 r S'",
      "U' l' U' L U' L F' L' F L' U2 l",
      "y' R' F' r U' r U' r' F r' F2 R",
      "y' R2 r U' R U' R' U2 R U' R r'",
      "y' R2 r U' R U' R' U2 R U' M",
      "y2 r U R' U R U2 B r' U L U2 L'",
      "y' r R2 U' R U' R' U2 R U' M",
      "y' L R2 F' R F' R' F2 R F' L' R",
      "y2 r U R' U R U2 x' U L' U L U2 L'",
      "y M U2 R' U' R U' R' U2 R U M'",
      "y R' U2 R2 U R' U' R' U2 F R2 U R' U' F'",
      "y' R' U' R U' R' U R S' R' U R S",
      "S F' U' F U' F' U2 F U' S'",
      "y2 U M' R' U' R U' R' U2 R U' M",
      "U l L2 U' L U' L' U2 L U' M'",
      "U' M' R' U' R U' R' U2 R U' M",
      "y3 R2 r U' R U' R' U2 R U' R r'",
      "y' R U R2 D' R U' R' D R2 U' R2 F R F'",
      "y2 S' U' r' F' r U' r' F2 r S",
      "y' R' F' r U' L F' L' F r' F2 R",
      "y r' R U2 R' U' R U' R' U2 R U R' r",
      "U' r R2 U' R U' R' U2 R U' R r'",
      "U l L2 U' L U' L' U2 L U' L l'",
      "y f' U' L' U L2 F L' U' L' U L S",
      "y f' U' r' F r2 U r' U' L' U L S",
      "R U R' U' R' F R F' U R U R' U' R' F R F'",
      "y' R' M' U' R U' R' U2 R U' R r'",
      "y' R B U' B' R2 D' r U r' D R",
      "y U2 r R2 U' R U' R' U2 R U' M",
      "y' R U R' U' R' F R2 U' R' U R U2 R' U' F'"
    ]
  },
  {
    "case": "OLL 13",
    "algorithms": [
      "F U R U2 R' U' R U R' F'",
      "F U R U' R2 F' R U R U' R'",
      "r U' r' U' r U r' F' U F",
      "y2 f R U R2 U' R' U R U' f'",
      "r U' r' U' r U r' y L' U L",
      "r U' r' U' r U r' y' R' U R",
      "L F' L' U' L F L' F' U F",
      "y2 R B' R' U' R B R' f' L f",
      "y2 F R U R2 U' R F' R' U R",
      "F U R U2 R' F R' F' R U F'",
      "y2 R' U' F' U F R U2 F U R U' R' F'",
      "y2 F R U R' U' R U' R' U' R U2 R' U' F'",
      "l' U' L U l F' L2 U' L U F",
      "L' U' L U R U R' U' L F' L' F R U R' U R U' R'",
      "y2 R' U' R U' r U R2 U R2 U2 r'",
      "L F' L' U' L F L' y' R' U R",
      "R U R' U' R' F R F' R U R' U R U2 R'",
      "S' L' U' L U L F' L2 U' L U f",
      "y' R U R' S' R U' R' S R' U2 R U R' U R",
      "R U R' U' M' U R U' M U R' U R U2 R'",
      "R U' L' U R' U' L R U R' S' R U' R' S",
      "y2 x' l F' l' F' l F l' U' F U",
      "y2 l U' l' U' l U l' f' L f",
      "y2 l U' l' U' l U l' B' U B",
      "y2 R B' R' U' R B R' B' U B",
      "S R U R' U R U2 R' U2 S' R U R' U' M' U R U' r'",
      "y x' U r' F' D' F r U' r' D r x",
      "y' x' D R' D' F' D R D' R' F R x",
      "y2 l U' l' U' l U l' y' L' U L",
      "r U' r' U' r U r' y z U' R U",
      "y' x U R' U' B' U R U' R' B R"
    ]
  },
  {
    "case": "OLL 14",
    "algorithms": [
      "R' F R U R' F' R F U' F'",
      "r U R' U' r' F R2 U R' U' F'",
      "l' U l U l' U' l F U' F'",
      "S R U R' U' R' F R2 U R' U' f'",
      "R' F R U R' F' R y L U' L'",
      "F' U' L' U L2 F L' U' L' U L",
      "y2 R U R' U' R' F R F' R U2 R' U' R U' R'",
      "y2 r' U r U r' U' r y R U' R'",
      "y2 r' U r U r' U' r f R' f'",
      "l' U l U l' U' l y' R U' R'",
      "F' U' L' U2 L U L' U' L F",
      "F' U' r' F2 r U' F R U' R'",
      "F' U' r' F r2 U r' U' r' F r",
      "R' F R U R' F' R y' R U' R'",
      "y F U R U' R' F' U2 R' U' F' U F R",
      "y2 F' L' U' L U L' U L U L' U2 L U F",
      "R' F R U l' U' l F U' F'",
      "R U R' U r' U' R2 U' R2 U2 r",
      "R U R' F' R U R' U' R' F R U' R' F R2 U R' U' F'",
      "F R U R' U' F2 r U R' U' r' F R",
      "F U R U' R2 F' R U2 R U' R' U R U2 R'",
      "F' U' L' U2 L F U' R' F R F'",
      "r' F R F' M' S' R U R' S",
      "y2 F U R U' R' F' R U R' U R U' R' U' R' F R F'",
      "r' F' r U' r' F2 r2 U R' U' r' R U R U' R'",
      "L' U2 R U R' U2 L U R' F R F'",
      "y2 r' U r U r' U' r B U' B'",
      "y2 r' U r U L' B' L B U' B'",
      "S' L' U' L U' L' U2 L U2 S R U R' U' M' U R U' r'",
      "y R U R' U R U' R' U R' F R F' R U2 R'",
      "y x' D' r F U F' r' D r U' r' x",
      "y2 f' L' U' L2 U L' f L U' L'",
      "L' U' L U L F' L' F L' U' L U' L' U2 L",
      "F R U' R' U R2 D R' U R D' R2 F'",
      "F R2 U D R2 D' R' D R' U' D' R2 F'",
      "y' x' U' R U F U' R' U R F' R'",
      "r' F R f' r U r' S M'"
    ]
  },
  {
    "case": "OLL 15",
    "algorithms": [
      "r' U' r R' U' R U r' U r",
      "y2 l' U' l L' U' L U l' U l",
      "r' U' M' U' R U r' U r",
      "y2 R' F' R L' U' L U R' F R"
    ]
  },
  {
    "case": "OLL 16",
    "algorithms": [
      "r U r' R U R' U' r U' r'",
      "r U M U R' U' r U' r'",
      "y2 R' F R U R' U' F' R U' R' U2 R",
      "y2 l U l' L U L' U' l U' l'",
      "R U' R' S R U' R' U S' U2 R U' R'",
      "L F L' R U R' U' L F' L'",
      "y' R' U' F' U F R F U R U' R' F'",
      "y S' L' U' L U L F' L' f l' U' L U' L' U2 l",
      "R' F R F' R U' R' U R U R' U F' U' F",
      "y2 l U M' U L' U' l U' l'",
      "R U R' U' R' F R2 U R' U' R' F' R U R U' R'",
      "R f R' F' R U R U' R' S' R'",
      "y2 F R U R' U' F' R U2 R' U' R U' R'",
      "f R U R' U' R U R' U' f' U' R U R' U R U2 R'",
      "y2 R U R' U' R' F R F' R U R' U R U' R' U R U2 R'",
      "y2 r U' r' U' r U r' y L' U' L U L' U L",
      "R U R' S R U R' U' S' R U' R'",
      "F' L' U' L U F y' L' U' L U' L' U2 L",
      "y' L U2 L' U' L F' U' L' U L F L'",
      "L F L' R U R' U' r U' r'",
      "y2 U2 r U r' R U R' U' r U' r'",
      "y' R' F' R f z' R' U' F U R f' z",
      "y x r' B' r U r' U' B U r U' x'",
      "y2 R B R' r B r' U' R B' R'",
      "y' z' F U S U B' U' F R' F'",
      "y2 R B R' L U L' U' R B' R'"
    ]
  },
  {
    "case": "OLL 17",
    "algorithms": [
      "R U R' U R' F R F' U2 R' F R F'",
      "y2 F R' F' R U S' R U' R' S",
      "y2 F R' F' R2 r' U R U' R' U' M'",
      "y' F' r U r' U' S r' F r S'",
      "y' f R U R' U' f' U R U R' U' R' F R F'",
      "y2 r U' r' F U2 F U' R U' R' F'",
      "f R U R' U' f' U' R U R' U' R' F R F'",
      "l U' l' f R2 B R' U R' U' f'",
      "F' r U r' U2 r' F U' F U r",
      "U2 F R' F' R U S' R U' R' S",
      "R B' R' f R2 B R' U R' U' f'",
      "y2 F R U' R' U' R U R' F' U R U R' U' M' U R U' r'",
      "y F U R U' R' U' R' F R F' R U R' F'",
      "y F R' F' R U2 R U' B U' B' R'",
      "y2 F R' F' R U R U' R' U R U R' U' M' U R U' r'",
      "y2 F U R U' R' F' U R U R' U' R' F R F'",
      "y' R' U' F' U F R2 U R' U' R' F R F'",
      "y L' U' L U' L F' L' F U2 L F' L' F",
      "y F U R U' R' F' U' R U R' U' R' F R F'",
      "y2 F R' F' R M U R U' R' U' M'",
      "U F U R U' R' U' R' F R F' R U R' F'",
      "y x' R U' R' U y' R S U R' U' S' z'",
      "y R' F' U2 F2 U R U' R' F' U2 R",
      "y2 F U R' U' F' U F R2 U R' U' F'",
      "y2 R' U' F U R U' R' F2 U' F U R",
      "r U' r U' r2 U r2 U r' R' U2 R U r'",
      "y' r' U r' U r2 U' r2 U' r R U2 R' U' r",
      "y' F R U2 R2 U' F' U F R U2 F'",
      "R U R' U x R' U R U' x' U2 x' z' U' R U R'",
      "B L' B' L2 l' U L U' L' U' M",
      "F' U' L' U L U L F' L' F L' U' L F",
      "U2 F R' F' R2 r' U R U' R' U' M'",
      "y2 r U' z U' R x' U2 R U' y R U' R' F'",
      "y2 r U R' U R U2 r' U2 r U2 R' U' R U' r'",
      "U2 r U' r' F U2 F U' R U' R' F'",
      "y' F' r U r' U' S L' U L S'",
      "y2 R U2 r' U' R U M' R' F2 r U r' F",
      "R' F R U' M' U2 r' U' F' U R"
    ]
  },
  {
    "case": "OLL 18",
    "algorithms": [
      "y R U2 R2 F R F' U2 M' U R U' r'",
      "r U R' U R U2 r2 U' R U' R' U2 r",
      "y F S' R U' R' S R U2 R' U' F'",
      "R D r' U' r D' R' U' R2 F R F' R"
    ]
  },
  {
    "case": "OLL 19",
    "algorithms": [
      "y S' R U R' S U' R' F R F'",
      "M U R U R' U' M' R' F R F'",
      "R' U2 F R U R' U' F2 U2 F R",
      "r' R U R U R' U' r R2 F R F'",
      "r' R U R U R' U' M' R' F R F'",
      "y2 r U2 R' U' R U' r2 U2 R U R' U r",
      "y2 F R' F' R U R U' R' U' F R U R' U' F'",
      "y' S r' F' r S' U r U' r' F",
      "M U R U R' U' r R2 F R F'",
      "r' U2 R U R' U r2 U2 R' U' R U' r'",
      "y F S' R U' R' S U R U R' F'",
      "y R U R' U' R' F R F' U2 r U R' U' r' R U R U' R'",
      "y2 F U R U' R2 F' U' F U R U' F'",
      "y' F U2 R' F' U' F U R2 U2 R' F'",
      "R r' U R U R' U' M' R' F R F'",
      "y S R U R' U' R' F R f' U R U R' U' M' U R U' r'",
      "y2 F R' F' R U R U' R2 F' U' F U R",
      "M U' L' U' L U M' L F' L' F",
      "y2 M' U' R' U' R U r' R l U' l' B",
      "y2 M' U' R' U' R U r' R l U' R' U x",
      "y2 M' U' R' U' R U r' R2 B' R' B",
      "F' L F L2 U L F R' F' R U' L' U L U R U' R'",
      "y' F R U' R' U' F R U R' U' F' R U R' F'",
      "U R U R' F' U' R U R' U' R' F R U' M' U R U' r'",
      "r' R U R U R' U' R2 r F R F'",
      "U2 F R' F' R U R U' R' U' F R U R' U' F'",
      "y2 l' U2 L U L' U l2 U2 L' U' L U' l'"
    ]
  },
  {
    "case": "OLL 20",
    "algorithms": [
      "r U R' U' M2 U R U' R' U' M'",
      "M' U2 M U2 M' U M U2 M' U2 M",
      "S' R U R' S U' M' U R U' r'",
      "S R' U' R U R U R U' R' S'",
      "M U R U R' U' M2 U R U' r'",
      "R U R' U' R' F R F' R U2 R2 F R F' R U2 R'",
      "M' U' M' U' M' U' M' U M' U' M' U' M' U' M' U'",
      "M' U2 M U2 M' U' M U2 M' U2 M",
      "r' R U R U R' U' R2 r2 U R U' r'",
      "M U M U M U M2 U M U M U M U M U M U M U M2 U M U M U M U",
      "S U' R U R' S2 R U' R' S",
      "R2 S' R2 U' S2 U' R2 S' R2",
      "S' R U R' S2 R U' R' U S'",
      "M' U' R' U' R U M2 U' R' U r",
      "M U M' U2 M U M' U M U M' U2 M U M'",
      "f R U R' U' f' R' F' U' F R U' R' U2 R",
      "r U R' U' M U R U' R' y R U R' U' M' U R U' r'",
      "F U R U' R' F' U2 R' U' R' F R F' U R",
      "M U M F R' F' M2 F R F'",
      "f R U R' U' f' R' U' R' F R F' U R",
      "r U R' U' r2 R2 U R U' R' U' M'",
      "M U' L' U' L U M2 U' L' U l",
      "r' R U R U R' U' L2 l2 U R U' r'",
      "r U R' U' M U S' R U' R' S",
      "M' U M' U M' U M' U' M' U M' U M' U M'",
      "M' U M' U M' U M' U M U M U M U M U",
      "M' U' M' U' M' U' M' U M' U' M' U' M' U' M' U",
      "r U R' U' M2 U R U' R' U' R' r",
      "R U R' U' M' U R U' r' U2 r U R' U' M U R U' R'",
      "F R' F R2 U R' U' F2 U' L F' L' F",
      "F R' F' R M2 R' F R F' M' U' M'",
      "M' U2 M U2 M' U' M U2 M' U2 M U",
      "M' U M U2 M' U M U M' U M U2 M' U M",
      "R U' R2 F2 U' R F' R' U F2 R2 U R'",
      "y F' L F M2 F' L' F M' U M'",
      "S R U R' U' R' U' R' U R S'",
      "r' R U R U R' U' M2 U R U' r'",
      "M' U' M U r U R' U' M U R U' R' U2 M' U2 M",
      "r U R' U' r' R U S' R U' R' S",
      "R U2 R' U' R U' R r' U R' U r U2 r' U M'",
      "U M' U M' U M' U M' U' M' U M' U M' U M'",
      "M' U' M U2 M' U' M U' M' U' M U2 M' U' M",
      "R' F R S2 R' F' R S' U S'",
      "r U R' U' r2 R2 U R U' R' U' R' r",
      "M U M U M U M U M' U M' U M' U M' U",
      "r' R U R U R' U' R' M' r U R U' r'",
      "r U R' U' r2 R2 U R U' R' U' r R'",
      "M' U2 M' U2 M' U M U2 M U2 M U",
      "R U' R2 F2 U' R F R' U F2 R2 U R'",
      "r U R' U' r R' M' U R U' R' U' M'",
      "r U R' U' R' M' r U R U' R' U' M'",
      "l' U' L U M2 U' L' U L U M'",
      "M' U' M' U' M' U' M' U' M U' M U' M U' M U'",
      "M U R U R' U' L2 l2 U R U' r'",
      "M U2 M' U2 M U M' U2 M U2 M'",
      "L R' F2 L' R U2 L R' F L' R U2 L R' F2 L' R",
      "M' U' M' U' M' U' M' U M' U' M' U' M' U' M'",
      "r' R U R U R' U' r2 R2 U R U' r'"
    ]
  },
  {
    "case": "OLL 21",
    "algorithms": [
      "R U R' U R U' R' U R U2 R'",
      "y R U2 R' U' R U R' U' R U' R'",
      "y F R U R' U' R U R' U' R U R' U' F'",
      "R' U' R U' R' U R U' R' U2 R",
      "y F U R U' R' U R U' R' U R U' R' F'",
      "y R' U2 R U R' U' R U R' U R",
      "y' F R U R' U' R U R' U' R U R' U' F'",
      "y F R U R' U' R U R' U' R U R' U' F' y'",
      "L U L' U L U' L' U L U2 L'",
      "R U R' U R U r' F R' F' r",
      "U y2 R2 U' L2 F2 L' F2 L D' F2 D' L D2 L' F2 L' F2 L D' F2 D' L D2 L U R2 y2 U'",
      "y R U2 D2 R' U' R U' R' U2 R D2 R' U y R U2 D2 R' U' R U' R' U2 R D2 R' U",
      "U' F R U R' U' R U R' U' R U R' U' F'",
      "y f U R U' R' U R U' R' U R U' R' f'",
      "y f R U R' U' R U R' U' R U R' U' f'",
      "U F R U R' U' R U R' U' R U R' U' F'",
      "y R' F2 R2 U2 R' F2 R U2 R2 F2 R",
      "y' R U2 R' U' R U R' U' R U' R'",
      "F R U' R' U R U2 R' U' R U R' U' F'",
      "R2 U' L2 F2 L' F2 L D' F2 D' L D2 L U R2",
      "U F R U R' U' R U R' U' R U R' U' F' U'",
      "y R' U' R U' R' U2 R F' r U R' U' r' F R",
      "L' U' L U' L' U L U' L' U2 L",
      "R U R' U R U2 U R' U R U2 R'",
      "L' U R U' L U R' U' R U2 R' U' R U' R'",
      "R B U B' U' B U B' U' B U B' U' R'",
      "y L' U2 L U L' U' L U L' U L",
      "U R U2 R' U' R U R' U' R U' R'",
      "U R U2 R' U' R U R' U2 R' F R2 U' R' U' R U R' F' U2",
      "U' f R U R' U' R U R' U' R U R' U' f'",
      "R U R' U R U L' U R' U' L",
      "f R U R' U' R F' R U R' U' R' S'",
      "R' F' R U2 R U2 R' F U' R U' R'"
    ]
  },
  {
    "case": "OLL 22",
    "algorithms": [
      "R U2 R2 U' R2 U' R2 U2 R",
      "R' U2 R2 U R2 U R2 U2 R'",
      "f R U R' U' S' R U R' U' F'",
      "f R U R' U' f' F R U R' U' F'",
      "y2 r' F2 r2 B r2 F r2 B2 r'",
      "y2 L' U2 L2 U L2 U L2 U2 L'",
      "R U R' U' R' U2 R U R' U R2 U2 R'",
      "y2 L U2 L2 U' L2 U' L2 U2 L",
      "y' R U R' U F' R U2 R' U2 R' F R",
      "y' R' U' R U' R' U2 R2 U2 R' U' R U' R'",
      "R U' L' U R' U' L U' R U R' U R U2 R'",
      "R' U' R U' R' U2 R U R' U' R U' R' U2 R",
      "F S R U R' U' S' R U R' U' F'",
      "y2 F R U R' U' R U R' U' S R U R' U' R U R' U' f'",
      "R U' z U' R D' R U R U' R U z'",
      "F R U R' U' R U R' U' F' R U R' U' M' U R U' r'",
      "y R U R' U R U2 R2 U2 R U R' U R",
      "y F R2 U' R2 U R2 U S R2 f'",
      "y' R' U2 R U R' U R2 U R' U R U2 R'",
      "U' r U R' U R' F R F' R U' R' U R U2 r'",
      "R U' L' U R' U L U L' U L",
      "y F U R U' R' U R U2 R' U' R U R' F'",
      "y F U R U' R' U R U' R2 F' R U R U' R'",
      "R U D' R U R' D R2 U' R' U' R2 U2 R",
      "y' R' U' R U' R' U2 R U' R' U' R U' R' U2 R",
      "R U2 R' U' R U' R' U' R U2 R' U' R U' R'",
      "R' F' U' F U' R U S' R' U R S",
      "y2 F U R U' R' F' U2 F R U R' U' F'",
      "R U R' U' R' F R2 U R' U' R U R' U' F'",
      "R2 D' R U R' D R U R U' R' U R U R' U R",
      "R U R' U R U2 R' U' R U R' U R U2 R'",
      "y R U R' U' L' U' L U' L' U L U' R U' R' U L' U L",
      "U' F U R U2 R' U R U R' F' R U2 R' U' R U' R'",
      "R' U' F' R U R' U' R' F R2 U2 R' U2 R",
      "y x' R U R' D R U' R' D' R U' R' D R U R' D' x",
      "R' U2 R U R' U R U R' U2 R U R' U R U",
      "y2 F U R U' R' S U R U' R' f'",
      "y2 L U' R' U L' U R U R' U R",
      "y2 L' U R U' L U' R' U' R U' R'",
      "y' R U2 R' U R' D' R U2 R' D R2 U' R'",
      "y2 r' F R F' r U' R' U' R U' R'"
    ]
  },
  {
    "case": "OLL 23",
    "algorithms": [
      "R2 D R' U2 R D' R' U2 R'",
      "y2 R2 D' R U2 R' D R U2 R",
      "R U R' U R U2 R2 U' R U' R' U2 R",
      "y R U R' U' R U' R' U2 R U' R' U2 R U R'",
      "y' R U2 R' U' R U' R' L' U2 L U L' U L",
      "R U R' U R U2 R' y R U2 R' U' R U' R' U",
      "R U' L U' R' U L' U2 R U' R'",
      "R2 D R' U2 R D' R' U2 D D' R'",
      "L2 D' L U2 L' D L U2 L",
      "y2 R' U2 R F U' R' U' R U F'",
      "y2 R' U2 R U2 R' F' R U R' U' R' F R2",
      "U F R U R' U' F' r U R' U' r' R U R U' R'",
      "y2 F R U' R' U R U R' U R U' R' F'",
      "R' F2 R U2 R U2 R' F2 R U2 R'",
      "U2 R2 D' R U2 R' D R U2 R",
      "y F U2 F' R' U F U F' U' R",
      "U2 R2 D' R U R' D R U R U' R' U' R",
      "R U R' U R U2 R' U R U2 R' U' R U' R'",
      "U r U R' U' r' F R F' R' F' L' F R F' L F",
      "y2 x' R U' R' D R U2 R' D' R U' R'",
      "R' D R D' R' D R U' R' D' R D R' D' R U",
      "y2 R' F R2 U' r' F R' F' r U R' F' R",
      "y2 L2 D L' U2 L D' L' U2 L'",
      "y2 R' U' R U' R' U2 R2 U R' U R U2 R'",
      "R U2 R' U L' U2 R U' R' U2 L",
      "y' R U' R' U R U' R' U2 R U R' U2 R U R' U R U R'",
      "x2 D' R U R' U' R U R' U' D' U R U' R' U R U' R' x2",
      "y2 R U' R' U' R U R D R' U R D' R2",
      "y' R U R2 F' r U R2 U' r' F U' R'",
      "f R U R' U' R f' U' r' U' R U M' f R U R' U' R f' U' r' U' R U M' U2",
      "y' U R' U2 L F2 L' F2 R2 U2 R U2 R' U2 F2 R2 F2 U' y",
      "y' R' D' R D R' D' R D U R' D' R D R' D' R D R' D' R D R' D' R D U'",
      "y' R U R' U R U' R' U' R' F R U R U' R' F'",
      "y2 l2 U' R D2 R' U R D2 R x2",
      "R U R' U R U2 R' U R U2 R' U' R U' R' U",
      "R' D R D' R' D R U' R' D' R D R' D' R",
      "U R' U' R U2 R D R' U2 R D' R2 U R",
      "U R U R' U2 R' D' R U2 R' D R2 U' R'",
      "y R U R' U' R U R' U' L' U R U' R' U R U' R' L",
      "U2 R' U' R U' R' U2 R2 U R' U R U2 R'",
      "y2 R' F R' F R2 U' R' U' R U R' F' R U R' U' F' R",
      "x' R U R' U' R U R' D R U' R' U R U' R' D' x",
      "y' R2 D' R U' R' D R2 U' R' U2 R",
      "y2 R' F R U' R' U' R U R' F' R U R' U' R' F R F' R",
      "R U' L' U R' U' L U2 L' U R U' L U R'",
      "R U2 x R U2 R U2 R' U2 L U2 r' U2 R U2 R' U2 R'",
      "y2 z U R2 U' F' R U R U' R' F z'",
      "y' R U2 R' U' R U' R' U' R U R' U R U2 R'",
      "R U2 x R U2 R U2 r' U2 L U2 R' U2 R U2 R' U2 R'",
      "U2 R' F R U' R' U' R U R' F' R U R' U' R' F R F' R",
      "R' U2 L F2 L' F2 R2 U2 R U2 R' U2 F2 R2 F2",
      "U' R U2 R' U' R U' R' U' R U R' U R U2 R'",
      "y2 R U R' U' R' F2 R2 U' R' U' R U R' F2",
      "x2 R2 U R' D2 R U' R' D2 R' x2",
      "R U R' U R U2 R' U2 L' U' L U' L' U2 L",
      "U' R' U' R U' R' U2 R U' R' U2 R' D' R U2 R' D R2 U",
      "R2 D R' U2 R D' R' U R U R U R U' R' U' R2 U2",
      "U' R U2 R' U' R U' R' U2 R' U2 R U R' U R",
      "U' R' U R' D' U' R U' R' U2 R U' R' D R U' R U'",
      "R U R' U R U2 R' y R U2 R' U' R U' R'",
      "y2 r U' r2 F R F' r U R' U' r U r'",
      "y F2 R U' R' U' R U R' F' R U R' U' R' F R F2",
      "R2 B2 U2 L U2 R' U2 R U2 F2 R F2 L' B2 R2",
      "y2 R' U2 R F' R' F U2 F' R F",
      "x R2 F R' B2 R F' R' B2 R'",
      "L' U' L U' L' U2 L2 U L' U L U2 L'",
      "y F R U R' U' R U R' U' F2 L' U' L U F"
    ]
  },
  {
    "case": "OLL 24",
    "algorithms": [
      "r U R' U' r' F R F'",
      "y2 R' F' r U R U' r' F",
      "y R U R D R' U' R D' R2",
      "y' x' R U R' D R U' R' D' x"
    ]
  },
  {
    "case": "OLL 25",
    "algorithms": [
      "R U2 R D R' U2 R D' R2",
      "y F' r U R' U' r' F R",
      "F R' F' r U R U' r'",
      "x R' U R D' R' U' R D x'"
    ]
  },
  {
    "case": "OLL 26",
    "algorithms": [
      "y R U2 R' U' R U' R'",
      "R' U' R U' R' U2 R",
      "y2 L' U' L U' L' U2 L",
      "y2 L' U R U' L U R'"
    ]
  },
  {
    "case": "OLL 27",
    "algorithms": [
      "R U R' U R U2 R'",
      "y' R' U2 R U R' U R",
      "y L' U2 L U L' U L",
      "y2 L U L' U L U2 L'"
    ]
  },
  {
    "case": "OLL 28",
    "algorithms": [
      "r U R' U' M U R U' R'",
      "r U R' U' r' R U R U' R'",
      "R' F R S R' F' R S'",
      "y2 M' U M U2 M' U M"
    ]
  },
  {
    "case": "OLL 29",
    "algorithms": [
      "r2 D' r U r' D r2 U' r' U' r",
      "y R U R' U' R U' R' F' U' F R U R'",
      "y S' R U R' U' R' F R F' U S",
      "M U R U R' U' R' F R F' M'"
    ]
  },
  {
    "case": "OLL 30",
    "algorithms": [
      "y' r' D' r U' r' D r2 U' r' U r U r'",
      "y2 F U R U2 R' U' R U2 R' U' F'",
      "y2 F R' F R2 U' R' U' R U R' F2",
      "y S' R' U' R f R' U R U' F'"
    ]
  },
  {
    "case": "OLL 31",
    "algorithms": [
      "R' U' F U R U' R' F' R",
      "y2 S' L' U' L U L F' L' f",
      "y S R U R' U' f' U' F",
      "y' F R' F' R U R U R' U' R U' R'"
    ]
  },
  {
    "case": "OLL 32",
    "algorithms": [
      "S R U R' U' R' F R f'",
      "y2 L U F' U' L' U L F L'",
      "R U B' U' R' U R B R'",
      "y' R' F R F' U' r U' r' U r U r'"
    ]
  },
  {
    "case": "OLL 33",
    "algorithms": [
      "R U R' U' R' F R F'",
      "y2 L' U' L U L F' L' F",
      "y2 r' F' r U r U' r' F",
      "R U R' F' U' F R U' R'"
    ]
  },
  {
    "case": "OLL 34",
    "algorithms": [
      "y f R f' U' r' U' R U M'",
      "y2 R U R2 U' R' F R U R U' F'",
      "F R U R' U' R' F' r U R U' r'",
      "y2 R U R' U' B' R' F R F' B"
    ]
  },
  {
    "case": "OLL 35",
    "algorithms": [
      "R U2 R2 F R F' R U2 R'",
      "f R U R' U' f' R U R' U R U2 R'",
      "R U2 R' d' R' F R U' R' F' R",
      "y L' U2 L2 F' L' F L' U2 L"
    ]
  },
  {
    "case": "OLL 36",
    "algorithms": [
      "y R U R2 F' U' F U R2 U2 R'",
      "y2 L' U' L U' L' U L U L F' L' F",
      "y2 R U R' F' R U R' U' R' F R U' R' F R F'",
      "R U R' U' F' U2 F U R U R'"
    ]
  },
  {
    "case": "OLL 37",
    "algorithms": [
      "F R' F' R U R U' R'",
      "F R U' R' U' R U R' F'",
      "y F' r U r' U' r' F r",
      "y2 r2 D' r U' r' D r U r"
    ]
  },
  {
    "case": "OLL 38",
    "algorithms": [
      "R U R' U R U' R' U' R' F R F'",
      "y F R U' R' S U' R U R' f'",
      "r U R' U' r' F R U R U' R' F'",
      "y2 L U L' U L U' L' U' L' B L B'"
    ]
  },
  {
    "case": "OLL 39",
    "algorithms": [
      "y' f' r U r' U' r' F r S",
      "y' R U R' F' U' F U R U2 R'",
      "y L F' L' U' L U F U' L'",
      "y' f' L F L' U' L' U L S"
    ]
  },
  {
    "case": "OLL 40",
    "algorithms": [
      "y R' F R U R' U' F' U R",
      "y' f R' F' R U R U' R' S'",
      "R r D r' U r D' r' U' R'",
      "y' L' U' L F U F' U' L' U2 L"
    ]
  },
  {
    "case": "OLL 41",
    "algorithms": [
      "y2 R U R' U R U2 R' F R U R' U' F'",
      "y2 F U R2 D R' U' R D' R2 F'",
      "y' S U' R' F' U' F U R S'",
      "M U' F' L' U' L U F M'"
    ]
  },
  {
    "case": "OLL 42",
    "algorithms": [
      "R' U' R U' R' U2 R F R U R' U' F'",
      "y F S' R U R' U' F' U S",
      "y R' F R F' R' F R F' R U R' U' R U R'",
      "y R' U' F2 u' R U R' D R2 B"
    ]
  },
  {
    "case": "OLL 43",
    "algorithms": [
      "y R' U' F' U F R",
      "y2 F' U' L' U L F",
      "f' L' U' L U f",
      "B' U' R' U R B"
    ]
  },
  {
    "case": "OLL 44",
    "algorithms": [
      "f R U R' U' f'",
      "y2 F U R U' R' F'",
      "y R U B U' B' R'",
      "y' L U F U' F' L'"
    ]
  },
  {
    "case": "OLL 45",
    "algorithms": [
      "F R U R' U' F'",
      "y R' F' U' F U R",
      "y2 f U R U' R' f'",
      "y2 F' L' U' L U F"
    ]
  },
  {
    "case": "OLL 46",
    "algorithms": [
      "R' U' R' F R F' U R",
      "R' F' U' F R U' R' U2 R",
      "y F R U R' U' F' U' R U R' U R U2 R'",
      "l' U2 L2 F' L' F U L' U l"
    ]
  },
  {
    "case": "OLL 47",
    "algorithms": [
      "y' F R' F' R U2 R U' R' U R U2 R'",
      "F' L' U' L U L' U' L U F",
      "R' U' R' F R F' R' F R F' U R",
      "y' R' F' U' F U F' U' F U R"
    ]
  },
  {
    "case": "OLL 48",
    "algorithms": [
      "F R U R' U' R U R' U' F'",
      "y2 f U R U' R' U R U' R' f'",
      "R U2 R' U' R U R' U2 R' F R F'",
      "F R' F' U2 R U R' U R2 U2 R'"
    ]
  },
  {
    "case": "OLL 49",
    "algorithms": [
      "y2 r U' r2 U r2 U r2 U' r",
      "l U' l2 U l2 U l2 U' l",
      "R B' R2 F R2 B R2 F' R",
      "y2 R' F R' F' R2 U2 B' R B R'"
    ]
  },
  {
    "case": "OLL 50",
    "algorithms": [
      "r' U r2 U' r2 U' r2 U r'",
      "y2 R' F R2 B' R2 F' R2 B R'",
      "y' R U2 R' U' R U' R' F R U R' U' F'",
      "y2 l' U l2 U' l2 U' l2 U l'"
    ]
  },
  {
    "case": "OLL 51",
    "algorithms": [
      "y2 F U R U' R' U R U' R' F'",
      "f R U R' U' R U R' U' f'",
      "y' R' U' R' F R F' R U' R' U2 R",
      "y r' F' U' F U F' U' F U r"
    ]
  },
  {
    "case": "OLL 52",
    "algorithms": [
      "y2 R' F' U' F U' R U R' U R",
      "R U R' U R U' B U' B' R'",
      "R U R' U R d' R U' R' F'",
      "R U R' U R U' y R U' R' F'"
    ]
  },
  {
    "case": "OLL 53",
    "algorithms": [
      "r' U' R U' R' U R U' R' U2 r",
      "y2 l' U' L U' L' U L U' L' U2 l",
      "y r' U2 R U R' U' R U R' U r",
      "y' l' U2 L U L' U' L U L' U l"
    ]
  },
  {
    "case": "OLL 54",
    "algorithms": [
      "r U R' U R U' R' U R U2 r'",
      "y' r U2 R' U' R U R' U' R U' r'",
      "y' r U r' R U R' U' R U R' U' r U' r'",
      "y2 l U L' U L U' L' U L U2 l'"
    ]
  },
  {
    "case": "OLL 55",
    "algorithms": [
      "y R' F U R U' R2 F' R2 U R' U' R",
      "y R' F R U R U' R2 F' R2 U' R' U R U R'",
      "R U2 R2 U' R U' R' U2 F R F'",
      "r U2 R2 F R F' U2 r' F R F'"
    ]
  },
  {
    "case": "OLL 56",
    "algorithms": [
      "r U r' U R U' R' U R U' R' r U' r'",
      "r U r' U R U' R' M' U R U2 r'",
      "F R U R' U' R F' r U R' U' r'",
      "r' U' r U' R' U R U' R' U R r' U r"
    ]
  },
  {
    "case": "OLL 57",
    "algorithms": [
      "R U R' U' M' U R U' r'",
      "y R U' R' S' R U R' S",
      "y R U R' S' R U' R' S",
      "R U R' U' R' r U R U' r'"
    ]
  }
]
