twolook_oll_algorithms = {
    "line": "F R U R' U' F'",
    "angle": "F U R U' R' F'",
    "dot": "F R U R' U' F' U2 F U R U' R' F'",
    "sune": "R U R' U R U2 R'",
    "anti-sune": "R U2 R' U' R U' R'",
    "h": "F R U R' U' R U R' U' R U R' U' F'",
    "pi": "R U2 R2 U' R2 U' R2 U2 R",
    "t": "R M' U R' U' R' M F R F'",
    "l": "F' R M' U R' U' R' M F R",
    "u": "R2 D R' U2 R D' R' U2 R'",
}

oll_algorithms = {
  "1": "R U2 R2 F R F' U2 R' F R F'",
  "2": "F R U R' U' F' R M U R' U' M'",
  "3": "R M U R' U' M' U' F R U R' U' F'",
  "4": "R M U R' U' M' U F R U R' U' F'",
  "5": "R' M U2 R U R' U R M",
  "6": "R M' U2 R' U' R U' R' M",
  "7": "R M' U R' U R U2 R' M",
  "8": "L M U' L U' L' U2 L M'",
  "9": "R U R' U' R' F R2 U R' U' F'",
  "10": "R U R' U R' F R F' R U2 R'",
  "11": "R M' U R' U R U' R' U' R' M R U R U' R'",
  "12": "M' R' U' R U' R' U2 R U' M",
  "13": "R M' U' R' M U' R M' U R' M F' U F",
  "14": "R' F R U R' F' R B U' B'",
  "15": "R' M U' R M' R' U' R U R' M U R M'",
  "16": "R M' U R' M R U R' U' R M' U' R' M",
  "17": "F R U R' U' F' R M' U R U' R' M",
  "18": "F R U R' U' R M U R' U' M' U' F'",
  "19": "M U R U R' U' M' R' F R F'",
  "20": "R M' U R' U' M2 U R U' R' U' M'",
  "21": "R U2 R' U' R U R' U' R U' R'",
  "22": "R U2 R2 U' R2 U' R2 U2 R",
  "23": "R2 D R' U2 R D' R' U2 R'",
  "24": "R M' U R' U' R' M F R F'",
  "25": "F' R M' U R' U' R' M F R",
  "26": "R U2 R' U' R U' R'",
  "27": "R U R' U R U2 R'",
  "28": "R M' U R' U' M U R U' R'",
  "29": "R2 U' R' U' R U R U R U' R",
  "30": "R2 U R' U R U' R' U' R' U R'",
  "31": "R' U' F U R U' R' F' R",
  "32": "R U B' U' R' U R B R'",
  "33": "R U R' U' R' F R F'",
  "34": "R U R' U' B' R' F R F' B",
  "35": "R U2 R2' F R F' R U2 R'",
  "36": "L' U' L U' L' U L U L F' L' F",
  "37": "F R' F' R U R U' R'",
  "38": "R U R' U R U' R' U' R' F R F'",
  "39": "L F' L' U' L U F U' L'",
  "40": "R' F R U R' U' F' U R",
  "41": "R U R' U R U2 R' F R U R' U' F'",
  "42": "R' U' R U' R' U2 R F R U R' U' F'",
  "43": "R M U R' U' M'",
  "44": "F U R U' R' F'",
  "45": "F R U R' U' F'",
  "46": "R' U' R' F R F' U R",
  "47": "F' L' U' L U L' U' L U F",
  "48": "F R U R' U' R U R' U' F'",
  "49": "R M' U' R2 M2 U R2 M2 U R2 M2 U' R M'",
  "51": "R M U R' U' M' U F R U R' U' F'",
  "52": "R U R' U R U' B U' B' R'",
  "53": "R' M U' R U' R' U R U' R' U2 R M'",
  "54": "R M' U R' U R U' R' U R U2 R' M",
  "55": "R' F R U R' U' F' U R",
  "56": "R M' U R' M U R U' R' U R U' R' R M' U' R' M",
  "57": "R U R' U' M' U R U' R' M"
}