pll_algorithms = {
    "Aa": "R' D R U2 R' D' R U' R' D R U' R' D' R",
    "Ab": "R2 B2 R F R' B2 R F' R",
    "F": "R' U' F' R U R' U' R' F R2 U' R' U' R U R' U R",
    "Ga": "R2 U R' U R' U' R U' R2 U' D R' U R D'",
    "Gb": "R' U' R U D' R2 U R' U R U' R U' R2 D",
    "Gc": "R2 U' R U' R U R' U R2 U D' R U' R' D",
    "Gd": "R U R' U' D R2 U' R U' R' U R' U R2 D'",
    "Ja": "L' U' L F L' U' L U L F' L2 U L",
    "Jb": "R U R' F' R U R' U' R' F R2 U' R'",
    "Ra": "R U' R' U' R U R D R' U' R D' R' U2 R'",
    "Rb": "R2 F R U R U' R' F' R U2 R' U2 R",
    "T": "R U R' U' R' F R2 U' R' U' R U R' F'",
    "E": "R2 U F' R' U R U' R' U R U' R' U R U' F U' R2",
    "Na": "R U R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R'",
    "Nb": "R' U R U' R' F' U' F R U R' F R' F' R U' R",
    "V": " R' U R' U' R D' R' D R' U D' R2 U' R2 D R2",
    "Y": "F R U' R' U' R U R' F' R U R' U' R' F R F'",
    "H": "M2 U M2 U2 M2 U M2",
    "Ua": "M2 U M U2 M' U M2",
    "Ub": "M2 U' M U2 M' U' M2",
    "Z": "M' U M2 U M2 U M' U2 M2",
}